---
title: "NCMH Master Data Dictionary"
author: "Daniel Oakes"
date: "`r Sys.Date()`"
output: 
  rmdformats::readthedown:
    code_folding: hide
    df_print: paged
    smart: false
---

```{r setup, include = FALSE}

knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(kableExtra)
library(rmdformats)
library(downloadthis)

```

## Alchemer Student Survey 

```{r, echo = FALSE}

alch_ss_2019 <- read.csv("../Individual_Surveys/Alchemer Student Survey 2019/Alchemer Student Survey 2019.csv")

```

Student survey data from 2019 and 2020. Including standardised scales PHQ-9, GADS-7, and WEMWBS-7. 

N Variables: `r nrow(alch_ss_2019)`

```{r, echo = FALSE}

# CSV File
download_file(
  path = "../Individual_Surveys/Alchemer Student Survey 2019/Alchemer Student Survey 2019.csv",
  output_name = "Alchemer Student Survey 2019",
  output_extension = ".csv",
  button_label = "Download CSV File",
  button_type = "success",
  has_icon = TRUE,
  icon = "fa fa-save",
  self_contained = FALSE
)

# PDF File
download_file(
  path = "../Individual_Surveys/Alchemer Student Survey 2019/Alchemer Student Survey 2019.pdf",
  output_name = "Alchemer Student Survey 2019",
  output_extension = ".pdf",
  button_label = "Download PDF File",
  button_type = "success",
  has_icon = TRUE,
  icon = "fa fa-save",
  self_contained = FALSE
)

```





